# Generated by Django 3.0.4 on 2020-03-21 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='idea',
            new_name='ideas',
        ),
    ]
