# Generated by Django 3.0.4 on 2020-03-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0002_auto_20200321_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
