# Generated by Django 3.0.4 on 2020-03-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0003_auto_20200321_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideas',
            options={'verbose_name_plural': 'ideas'},
        ),
    ]
