# Generated by Django 3.0.4 on 2020-03-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0006_auto_20200328_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairwise_results',
            name='new_lose_elo',
            field=models.SmallIntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='pairwise_results',
            name='new_win_elo',
            field=models.SmallIntegerField(default=1500),
        ),
    ]
